name: Generate Database Schema

on:
  push:
    branches:
      - main

jobs:
  generate-schema:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre graphviz

      # Step 3: Make the script executable
      - name: Make script executable
        run: chmod +x ./generate_schema.sh

      # Step 4: Run the script
      - name: Run SchemaSpy script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: ./generate_schema.sh

      # Step 5: Delete older directories in the repository
      - name: Delete older schema directories
        run: |
          cd generated
          ls -dt */ | tail -n +8 | xargs rm -rf
        continue-on-error: true

      # Step 6: Commit generated files
      - name: Commit generated files
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add generated/*
          git commit -m "Update generated schema files" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
