# .github/workflows/main.yml

name: Generate Database Schema

on:
  push:
    branches:
      - main

jobs:
  generate-schema:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre graphviz

      # Step 3: Make the script executable
      - name: Make script executable
        run: chmod +x ./generate_schema.sh

      # Step 4: Run the script
      - name: Run SchemaSpy script
        run: ./generate_schema.sh
