name: Generate Database Schema

on:
  push:
    branches:
      - main

jobs:
  generate-schema:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run SchemaSpy using Docker
      - name: Run SchemaSpy script in Docker
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |
          docker pull anytyng123/java-graphviz-image:latest
          docker run --rm \
            -e DB_HOST="${{ secrets.DB_HOST }}" \
            -e DB_PORT="${{ secrets.DB_PORT }}" \
            -e DB_NAME="${{ secrets.DB_NAME }}" \
            -e DB_USER="${{ secrets.DB_USER }}" \
            -e DB_PASS="${{ secrets.DB_PASS }}" \
            -v ${{ github.workspace }}:/workspace \
            anytyng123/java-graphviz-image:latest \
            bash -c "mkdir -p /workspace/generated && /workspace/generate_schema.sh"

      # Step 3: Commit generated files
      - name: Commit generated files
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add generated/*
          git commit -m "Update generated schema files" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
