# .github/workflows/main.yml

name: Generate Database Schema

on:
  push:
    branches:
      - main

jobs:
  generate-schema:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre graphviz

      # Step 3: Make the script executable
      - name: Make script executable
        run: chmod +x ./generate_schema.sh

      # Step 4: Run the script
      - name: Run SchemaSpy script
        run: ./generate_schema.sh
        
      # Step 5: Commit generated files
      - name: Commit generated files
        run: |
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
         git checkout -b schema-update-branch
         git add generated/*
         git commit -m "Update generated schema files" || echo "No changes to commit"
       
       # Fetch latest changes from the remote main branch
         git fetch origin main
       # Rebase the current branch on top of main
         git rebase origin/main
       # Push the changes
         git push origin schema-update-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


