# .github/workflows/main.yml

name: Generate Database Schema

on:
  push:
    branches:
      - main

jobs:
  generate-schema:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Make the script executable
      - name: Make script executable
        run: chmod +x ./generate_schema.sh
        # If your script is in a different folder, update the path:
        # run: chmod +x ./scripts/generate_schema.sh

      # Step 3: Run the script
      - name: Run SchemaSpy script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: ./generate_schema.sh
        # If your script is in a different folder, update the path:
        # run: ./scripts/generate_schema.sh
